// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBljYoKFf7_A9uZvCGDF99q3dpz_DOC-60',
    appId: '1:605027721323:android:2b3baa9809cc98da79512e',
    messagingSenderId: '605027721323',
    projectId: 'moneytine-4f705',
    storageBucket: 'moneytine-4f705.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkp4GdPav4AOYA-KJFRt1tm0YyxR-vQio',
    appId: '1:605027721323:ios:32f7bb12d5c3b0ef79512e',
    messagingSenderId: '605027721323',
    projectId: 'moneytine-4f705',
    storageBucket: 'moneytine-4f705.appspot.com',
    androidClientId: '605027721323-0u79tu8g4nibrkkhlhp64f87uia4dnfr.apps.googleusercontent.com',
    iosClientId: '605027721323-hoe4kck2bd4c1vc31u6dgqj3b4dpjptv.apps.googleusercontent.com',
    iosBundleId: 'com.digifaz.moneytine',
  );
}
